"""Shared contracts and data transfer objects for Personal Task Board."""

from ptb_contracts.l1_acquisition import (
    AgentType,
    IngestionCheckpointRecord,
    ProcessingAttemptRecord,
    ProcessingStatus,
    RawAgentSessionRecord,
    RawEventRecord,
    SourceConnectionConfig,
    SourceType,
    SyncCheckpointState,
)
from ptb_contracts.l2_processing import (
    CommitmentRecord,
    EvidenceRecord,
    EvidenceType,
    ExtractedCommitment,
    InferredStatus,
    ParsedMessageContent,
    ReviewQueueItem,
    StatusTransitionAuditRecord,
    TaskStatus,
    UnifiedTaskCandidate,
)
from ptb_contracts.l3_storage import (
    CanonicalPersonRecord,
    CommitmentNodeRecord,
    CustomerRecord,
    DecisionNodeRecord,
    DocumentNodeRecord,
    EvidenceNodeRecord,
    GraphNeighborhoodQuery,
    IncidentNodeRecord,
    LessonNodeRecord,
    ProjectRecord,
    SourceIdentityRecord,
    TenantRecord,
    UnifiedTaskRecord,
)
from ptb_contracts.l4_intelligence import (
    DecisionRecord,
    ForgottenCommitmentItem,
    GraphRelationInfo,
    LessonRecord,
    PriorityBreakdown,
    TaskWithContext,
    TodayBoardView,
    TodayTaskItem,
    WaitingOnItem,
)
from ptb_contracts.l5_experience import (
    CoverageStatusResponse,
    CoverageTenantStatus,
    KnowledgeSearchRequest,
    KnowledgeSearchResponse,
    MCPToolCallRequest,
    MCPToolCallResult,
    ReviewActionResponse,
    TaskActionResponse,
)

__all__ = [
    # L1
    "SourceType",
    "AgentType",
    "ProcessingStatus",
    "RawEventRecord",
    "RawAgentSessionRecord",
    "IngestionCheckpointRecord",
    "ProcessingAttemptRecord",
    "SourceConnectionConfig",
    "SyncCheckpointState",
    # L2
    "TaskStatus",
    "InferredStatus",
    "EvidenceType",
    "ParsedMessageContent",
    "EvidenceRecord",
    "CommitmentRecord",
    "ExtractedCommitment",
    "UnifiedTaskCandidate",
    "StatusTransitionAuditRecord",
    "ReviewQueueItem",
    # L3
    "CanonicalPersonRecord",
    "SourceIdentityRecord",
    "UnifiedTaskRecord",
    "EvidenceNodeRecord",
    "CommitmentNodeRecord",
    "ProjectRecord",
    "CustomerRecord",
    "TenantRecord",
    "DecisionNodeRecord",
    "LessonNodeRecord",
    "IncidentNodeRecord",
    "DocumentNodeRecord",
    "GraphNeighborhoodQuery",
    # L4
    "GraphRelationInfo",
    "TaskWithContext",
    "PriorityBreakdown",
    "TodayTaskItem",
    "ForgottenCommitmentItem",
    "WaitingOnItem",
    "TodayBoardView",
    "DecisionRecord",
    "LessonRecord",
    # L5
    "TaskActionResponse",
    "ReviewActionResponse",
    "CoverageTenantStatus",
    "CoverageStatusResponse",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResponse",
    "MCPToolCallRequest",
    "MCPToolCallResult",
]
